config = {
	"ALTERNATIVE_LOCAL_PYTHON_MODULES_PATH": "YOUR CONFIGURATION HERE",
	"PACKT_EMAIL": "YOUR CONFIGURATION HERE",
	"PACKT_PASSWORD": "YOUR CONFIGURATION HERE",
	"USER_EMAIL": "YOUR CONFIGURATION HERE"
}